version: '3'

services:
  jupyter:
    build: ./jupyter
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    ports:
      - "58888:8888"
  neo4j:
    image: neo4j
    restart: always
    ports:
      - 57474:7474
      - 57687:7687
    expose:
      - 7687
    volumes:
      - ./neo4j:/data